COMMON_SOURCES=
SERVER_SOURCES=$(COMMON_SOURCES) server.c
CLIENT_SOURCES=$(COMMON_SOURCES) client.c

CC=gcc
CFLAGS=-Wall -Werror -Wextra
CLIENT_LDFLAGS=-lSDL2 -luv
SERVER_LDFLAGS=-luv

SERVER_OBJECTS=$(SERVER_SOURCES:.c=.o)
CLIENT_OBJECTS=$(CLIENT_SOURCES:.c=.o)

CLIENT_TARGET=client
SERVER_TARGET=server

all: $(SERVER_TARGET) $(CLIENT_TARGET)

$(SERVER_TARGET): $(SERVER_OBJECTS)
	$(CC) $(SERVER_LDFLAGS) $^ -o $@

$(CLIENT_TARGET): $(CLIENT_OBJECTS)
	$(CC) $(CLIENT_LDFLAGS) $^ -o $@

.c.o:
	$(CC) $(CLFAGS) -c $^ -o $@

clean:
	$(RM) $(CLIENT_OBJECTS) $(SERVER_OBJECTS) $(CLIENT_TARGET) $(SERVER_TARGET)

